AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Scrumble backend - DynamoDB + Lambda

Parameters:
  AdminKey:
    Type: String
    NoEcho: true
    Description: Admin API key for /admin endpoints

Globals:
  Function:
    Timeout: 10
    Runtime: python3.12
    Architectures:
      - arm64

Resources:
  ScrumbleTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: scrumble-data
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE

  ScrumbleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/
      Handler: app.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref ScrumbleTable
          ADMIN_KEY: !Ref AdminKey
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ScrumbleTable
        - Statement:
          - Effect: Allow
            Action:
              - cloudwatch:PutMetricData
            Resource: '*'
      FunctionUrlConfig:
        AuthType: NONE

Outputs:
  FunctionUrl:
    Description: Lambda Function URL
    Value: !GetAtt ScrumbleFunctionUrl.FunctionUrl
  TableName:
    Description: DynamoDB Table
    Value: !Ref ScrumbleTable
